title: Product

columns:
  - width: 1/3
    sections:
      media:
        headline: Images
        type: files
        template: image
        sortable: true

  - width: 2/3
    sections:
      settings:
        type: fields
        fields:
          settingsheadline:
            label: General
            type: headline

          picture:
            label: Image
            type: files
            multiple: false
            upload:
              template: image
            width: 1/2
            required: true
            translate: false

          price:
            label: Price
            type: text
            width: 1/3
            required: true
            disabled: true
            translate: false