title: Product

columns:
  - width: 1/3
    sections:
      media:
        headline: Media
        type: files
        template: image
        sortable: true

  - width: 2/3
    sections:
      settings:
        type: fields
        fields:
          settingsheadline:
            label: General
            type: headline

          name:
            label: Name
            type:  text
            width: 2/3
            required: true

          articleId:
            label: Article ID
            type: text
            width: 1/3
            required: true

          price:
            label: Price
            type: text
            width: 1/4
            required: true

          packagingUnit:
            label: Packaging unit
            type: text
            width: 1/4
            required: true

          cover:
            label: Picture
            type: files
            multiple: false
            upload:
              template: image
            required: true
            width: 1/2

          dimensionsheadline:
            label: Colors & dimensions
            type: headline

          colors:
            label: Colors
            type:  checkboxes
            columns: 3
            options:
              color1: White (1)
              color2: Blue (2)
              color3: Red (3)
              color4: Yellow (4)
              color5: Green (5)
              color6: Black (6)
              color7: Orange (7)
              color8: Purple (8)
              color9: Pink (9)
              color11: Grey (11)
              color12: Brown (12)
            required: true

          line1:
            type: line

          dimensions:
            label: Dimensions
            type: toggle
            text:
              - "No"
              - "Yes"
            width: 1/3

          length:
            label: Length (mm)
            type: text
            width: 1/3
            when:
              dimensions: true

          width:
            label: Width (mm)
            type: text
            width: 1/3
            when:
              dimensions: true

          bristles:
            label: Bristles / Trimmings
            type: toggle
            text:
              - "No"
              - "Yes"
            width: 1/3

          bristleLength:
            label: Bristle length (mm)
            type: text
            width: 1/3
            when:
              bristles: true

          bristleWidth:
            label: Bristle strength (mm)
            type: text
            width: 1/3
            when:
              bristles: true

          usageheadline:
            label: Usage
            type: headline

          usage:
            label: Usage type
            type: select
            options:
              sweeping: Sweeping
              brushing: Brushing
              liquids: Liquid removal
              special: Special usage
            width: 1/3
            default: sweeping

          sweeping:
            label: Sweeping usage
            type: checkboxes
            options:
              sweeping1: Fine dirt
              sweeping2: Medium dirt
              sweeping3: Coarse dirt
              sweeping4: Very coarse dirt
            width: 1/3
            when:
              usage: sweeping

          brushing:
            label: Brushing usage
            type: checkboxes
            options:
              brushing1: Loose dirt
              brushing2: Medium dirt
              brushing3: Stubborn dirt
              brushing4: Very stubborn dirt
            width: 1/3
            when:
              usage: brushing

          surfaces:
            label: Appropriate surfaces
            type: checkboxes
            options:
              brushing1: Smooth surfaces
              brushing2: Structured surfaces
              brushing3: Rough surfaces
              brushing4: Very rough surfaces
            width: 1/3

          line2:
            type: line

          properties:
            label: Properties
            type: checkboxes
            options:
              phb: PHB-approved
              stainless: Stainless steel
              alcalics: Suitable for alcalic solutions
              acids: Suitable for acids
              waterflow: Water-flow function
              partiallyDetectable: Detectable filaments
              fullyDetectable: Fully detectable
            columns: 2

