title: Product

columns:
  - width: 1/3
    sections:
      media:
        headline: Media
        type: files
        template: image
        sortable: true

  - width: 2/3
    sections:
      settings:
        type: fields
        fields:
          settingsheadline:
            label: General
            type: headline

          name:
            label: Name
            type:  text
            width: 2/3
            required: true

          articleId:
            label: Article ID
            type: text
            width: 1/3
            required: true

          price:
            label: Price
            type: text
            width: 1/3
            required: true

          packagingUnit:
            label: Packaging unit
            type: text
            width: 1/3
            required: true

          dimensionsheadline:
            label: Colors & dimensions
            type: headline

          pictureColor1:
            label: Picture (Color 1 - white)
            type: files
            multiple: false
            upload:
              template: image
            width: 1/2

          pictureColor2:
            label: Picture (Color 2 - blue)
            type: files
            multiple: false
            upload:
              template: image
            width: 1/2

          pictureColor3:
            label: Picture (Color 3 - red)
            type: files
            multiple: false
            upload:
              template: image
            width: 1/2

          pictureColor4:
            label: Picture (Color 4 - yellow)
            type: files
            multiple: false
            upload:
              template: image
            width: 1/2

          pictureColor5:
            label: Picture (Color 5 - green)
            type: files
            multiple: false
            upload:
              template: image
            width: 1/2

          pictureColor6:
            label: Picture (Color 6 - black)
            type: files
            multiple: false
            upload:
              template: image
            width: 1/2

          pictureColor7:
            label: Picture (Color 7 - orange)
            type: files
            multiple: false
            upload:
              template: image
            width: 1/2

          pictureColor8:
            label: Picture (Color 8 - purple)
            type: files
            multiple: false
            upload:
              template: image
            width: 1/2

          pictureColor9:
            label: Picture (Color 9 - pink)
            type: files
            multiple: false
            upload:
              template: image
            width: 1/2

          pictureColor11:
            label: Picture (Color 11 - grey)
            type: files
            multiple: false
            upload:
              template: image
            width: 1/2

          pictureColor12:
            label: Picture (Color 12 - brown)
            type: files
            multiple: false
            upload:
              template: image
            width: 1/2

          line1:
            type: line

          dimensions:
            label: Dimensions
            type: toggle
            text:
              - "No"
              - "Yes"
            width: 1/3

          length:
            label: Length (mm)
            type: text
            width: 1/3
            when:
              dimensions: true

          width:
            label: Width (mm)
            type: text
            width: 1/3
            when:
              dimensions: true

          bristles:
            label: Bristles / Trimmings
            type: toggle
            text:
              - "No"
              - "Yes"
            width: 1/3

          bristleLength:
            label: Bristle length (mm)
            type: text
            width: 1/3
            when:
              bristles: true

          bristleWidth:
            label: Bristle strength (mm)
            type: text
            width: 1/3
            when:
              bristles: true

          maxTemperature:
            label: Max. temperature (°)
            type: text
            width: 1/3

          usageheadline:
            label: Usage
            type: headline

          usage:
            label: Usage type
            type: select
            options:
              sweeping: Sweeping
              brushing: Brushing
              liquids: Liquid removal
              special: Special usage
            width: 1/3
            default: sweeping

          sweeping:
            label: Sweeping usage
            type: checkboxes
            options:
              sweeping1: Fine dirt
              sweeping2: Medium dirt
              sweeping3: Coarse dirt
              sweeping4: Very coarse dirt
            width: 1/3
            when:
              usage: sweeping

          brushing:
            label: Brushing usage
            type: checkboxes
            options:
              brushing1: Loose dirt
              brushing2: Medium dirt
              brushing3: Stubborn dirt
              brushing4: Very stubborn dirt
            width: 1/3
            when:
              usage: brushing

          surfaces:
            label: Appropriate surfaces
            type: checkboxes
            options:
              surface1: Smooth surfaces
              surface2: Structured surfaces
              surface3: Rough surfaces
              surface4: Very rough surfaces
            width: 1/3

          line2:
            type: line

          properties:
            label: Properties
            type: checkboxes
            options:
              phb: PHB-approved
              stainless: Stainless steel
              alcalics: Suitable for alcalic solutions
              acids: Suitable for acids
              waterflow: Water-flow function
              partiallyDetectable: Detectable filaments
              fullyDetectable: Fully detectable
            columns: 2

