title: Product

columns:
  - width: 1/3
    sections:
      productvariants:
        headline: Product variants
        type: pages
        template: productvariant
        sortBy: name asc
        sortable: false
        min: 1
        max: 11
        help: Variants need to be named with color numbers.

  - width: 2/3
    sections:
      settings:
        type: fields
        fields:
          settingsheadline:
            label: General
            type: headline

          name:
            label: Name
            type:  text
            width: 2/3
            required: true

          articleId:
            label: Article ID
            type: text
            width: 1/3
            required: true

          price:
            label: Price
            type: text
            width: 1/3
            required: true

          tax:
            label: Tax
            type: select
            options:
              20: 20%
            default: 20
            width: 1/3
            required: true

          packagingUnit:
            label: Packaging unit
            type: text
            width: 1/3
            required: true

          dimensionsheadline:
            label: Colors & dimensions
            type: headline

          weight:
            label: Weight (g)
            type: text
            width: 1/3
            required: true

          line1:
            type: line

          dimensions:
            label: Dimensions
            type: toggle
            text:
              - "No"
              - "Yes"
            width: 1/3

          length:
            label: Length (mm)
            type: text
            width: 1/3
            when:
              dimensions: true

          width:
            label: Width (mm)
            type: text
            width: 1/3
            when:
              dimensions: true

          bristles:
            label: Bristles / Trimmings
            type: toggle
            text:
              - "No"
              - "Yes"
            width: 1/3

          bristleLength:
            label: Bristle length (mm)
            type: text
            width: 1/3
            when:
              bristles: true

          bristleWidth:
            label: Bristle strength (mm)
            type: text
            width: 1/3
            when:
              bristles: true

          maxTemperature:
            label: Max. temperature (°)
            type: text
            width: 1/3

          usageheadline:
            label: Usage
            type: headline

          usage:
            label: Usage type
            type: select
            options:
              sweeping: Sweeping
              brushing: Brushing
              liquids: Liquid removal
              special: Special usage
            width: 1/3
            default: sweeping

          sweeping:
            label: Sweeping usage
            type: checkboxes
            options:
              sweeping1: Fine dirt
              sweeping2: Medium dirt
              sweeping3: Coarse dirt
              sweeping4: Very coarse dirt
            width: 1/3
            when:
              usage: sweeping
            required: true
            translate: false

          brushing:
            label: Brushing usage
            type: checkboxes
            options:
              brushing1: Loose dirt
              brushing2: Medium dirt
              brushing3: Stubborn dirt
              brushing4: Very stubborn dirt
            width: 1/3
            when:
              usage: brushing
            required: true
            translate: false

          surfaces:
            label: Appropriate surfaces
            type: checkboxes
            options:
              surface1: Smooth surfaces
              surface2: Structured surfaces
              surface3: Rough surfaces
              surface4: Very rough surfaces
            width: 1/3
            translate: false

          line2:
            type: line

          properties:
            label: Properties
            type: checkboxes
            options:
              phb: PHB-approved
              stainless: Stainless steel
              alcalics: Suitable for alcalic solutions
              acids: Suitable for acids
              waterflow: Water-flow function
              partiallyDetectable: Detectable filaments
              fullyDetectable: Fully detectable
            columns: 2

