title: Product category

columns:
  - width: 1/3
    sections:
      productcategories:
        headline: Product subcategories
        type: pages
        templates:
          - productcategory
        sortable: true

      products:
        headline: Products
        type: pages
        templates:
          - product
        sortable: true

  - width: 2/3
    sections:
      settings:
        type: fields
        fields:
          title:
            label: Title
            type:  text

          settingsheadline:
            label: Site settings
            type: headline

          name:
            label: Category name
            type:  text
            required: true