title: Site

columns:
  - width: 1/3
    sections:
      products:
        headline: Products
        type: pages
        templates:
          - product
        sortable: true

      pages:
        headline: Pages
        type: pages
        templates:
          - home
          - search
        sortable: true

      files:
        headline: Files
        type: files
        sortable: true

  - width: 2/3
    sections:
      settings:
        type: fields
        fields:
          title:
            label: Title
            type:  text

          settingsheadline:
            label: Site settings
            type: headline

          name:
            label: Site name
            type:  text
            required: true

      meta:
        type: fields
        fields:
          metaheadline:
            label: Meta data
            type: headline

          author:
            label: Authors
            type:  text
            translate: false
            required: true

          description:
            label: Description
            type:  textarea
            help: This serves as a short description of your site for search engine previews.
            required: true

          keywords:
            label: Keywords
            type:  text
            help: Use comma-seperated keywords to aid search engines in finding your site.
            required: true
      
      contact:
        type: fields
        fields:
          contactheadline:
            label: Contact info
            type: headline

          email:
            label: Email address
            type:  text
            width: 1/2
            translate: false

          phone:
            label: Phone number
            type:  text
            width: 1/2
            translate: false

          address:
            label: Address
            type:  textarea
            translate: false

          contactPage:
            label: Contact page
            type: pages
            width: 1/2
            multiple: false
            translate: false
            help: If your site features a dedicated contact page linked in the footer or other repeating elements, this is where you can set that link.

          contactSection:
            label: Contact section
            type: text
            width: 1/2
            multiple: false
            translate: false
            help: If your site features a dedicated section on a contact page linked in the footer or other repeating elements, this is where you can set the section id.

      #social:
        #type: fields
        #fields:
          #socialheadline:
            #label: Social networks
            #type: headline  

          #facebook:
            #label: Facebook URL
            #type:  text
            #width: 1/2
            #translate: false

          #instagram:
            #label: Instagram URL
            #type:  text
            #width: 1/2
            #translate: false

          #twitter:
            #label: Twitter URL
            #type:  text
            #width: 1/2
            #translate: false

          #linkedIn:
            #label: LinkedIn URL
            #type:  text
            #width: 1/2
            #translate: false

          #socialLine:
            #type: line

          #newslettercall:
            #label: Newsletter signup text
            #type: textarea
            #help: If your site features repeating calls to action advertising your newsletter, this is where you can set the corresponding text.

          #newsletter:
            #label: Newsletter signup URL
            #type: text
            #width: 1/2
            #translate: false
            #help: If you're using a newsletter service which features an external dedicated signup page, this link can be configured here.

      footer:
        type: fields
        fields:
          footerheadline:
            label: References & legal info
            type: headline

          copyright:
            label: Copyright
            type:  text
            width: 1/3
            translate: false
            help: Insert the copyright holder of your website here.

          design:
            label: Design
            type:  text
            width: 1/3
            translate: false
            help: Help out your design studio by naming them here.

          designLink:
            label: Design link
            type:  text
            width: 1/3
            translate: false
            help: Help out your design studio by placing a link to their website here.

          footerLine:
            type: line

          cookieHeadline:
            label: Cookie pop-up headline
            type:  text
            width: 1/2
            required: true

          cookieText:
            label: Cookie pop-up text
            type:  textarea
            required: true

          termsConditionsFile:
            label: Terms & conditions / legal notice (file)
            type: files
            query: site.files
            multiple: false
            translate: false
            width: 1/2
            help: If your site supplies the terms & conditions as a file (f.e. in PDF format), link this file here.

          termsConditionsPage:
            label: Terms & conditions / legal notice (page)
            type: pages
            query: site.pages
            multiple: false
            translate: false
            width: 1/2
            help: If your site supplies the terms & conditions in the form of a page, link that page here.

          cookiePolicyFile:
            label: Cookie policy (file)
            type: files
            query: site.files
            multiple: false
            translate: false
            width: 1/2
            help: If your site supplies the terms & conditions as a file (f.e. in PDF format), link this file here.

          cookiePolicyPage:
            label: Cookie policy (page)
            type: pages
            query: site.pages
            multiple: false
            translate: false
            width: 1/2
            help: If your site supplies the cookie policy in the form of a page, link that page here.

          #legalNoticePage:
            #label: Legal notice (page)
            #type: pages
            #query: site.pages
            #multiple: false
            #translate: false
            #width: 1/2
            #help: If your site features a dedicated legal notice page linked in the footer or other repeating elements, this is where you can set that link.

          #legalNoticeFile:
            #label: Legal notice (file)
            #type: files
            #query: site.files
            #multiple: false
            #translate: false
            #width: 1/2
            #help: If your site supplies the legal notice as a file (f.e. in PDF format), link this file here.